name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Buildx
        run: docker buildx build --platform linux/amd64 --tag arduino-processing .