name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Build Docker image
        uses: docker/build-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64