name: draft release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-draft:
    runs-on: ubuntu-latest

    steps:
      - name: Define Version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Draft Release
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.vars.outputs.tag }}
          version: ${{ steps.vars.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
